### ISSUE TITLE
make [kaskadi init] run on github-action

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/template-kaskadi-element#3]
make `kaskadi init` run on github-action when new repository is created

**Comment by Holger-Will** [comment]
wen can use the following event/filter:

```
on:
  create:
    branches:
      - master
```
this only runs when the master branch is created (before the first pull) \o/
